config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  unauthenticated :user do
    root to: "pages#home"
  end
  authenticated do
    root to: "houses#index", as: :authenticated_root
  end
  # get "pages/home", to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:update], as: "update"
  get "pages/dashboard", to: "pages#dashboard"

  resources :users do
    get "pages/profile", to: "pages#profile"
    member do
      put "picture_update"
    end
  end

  resources :houses, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
    resources :notifications, only: [:new, :create]
  end

  delete "notifications/:id", to: "notifications#destroy", as: "delete_notification"

  resources :notifications, only: [:index, :show] do
    collection do
      get :user_personal
    end
  end

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end

  resources :bookings, only: [:index] do
    resources :chatrooms, only: :create
    collection do
      get :my
    end
  end
  resources :notification_panels, only: :show
end

app/views/shared/_house_guest_show.html.erb
 <div class="container p-4">
    <div class="d-flex justify-content-center">
      <% if @house.photos.attached? %>
        <% @house.photos.each do |photo| %>
          <%= image_tag photo, width: "400px", class: "show-house-img" %>
        <% end %>
      <% else %>
        <%= image_tag "house_placeholder.png", width: "400px" %>
      <% end %>
    </div>
  </div>
  <div class="container d-flex justify-content-around">
    <div id="house-details">
      <div>
        <h2>Info:</h2>
        <ul>
          <li> <strong>Name:</strong> <%= @house.name %> </li>
          <li> <strong>Description: </strong><%= @house.description %> </li>
          <li><strong>City:</strong> <%= @house.city %> </li>
          <li><strong>Country:</strong> <%= @house.country %> </li>
          <li><strong>Price:</strong> <%= @house.price_per_night %>€/night </li>
        </ul>
        <h2>Rules:</h2>
        <ul>
          <% @rules.each do |rule| %>
            <li> <%= rule %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div id="host-details">
      <h2>Host:</h2>
      <% if @house.user.picture.attached? %>
        <%= image_tag @house.user.picture_thumbnail, width: "80px", class: "rounded-circle mx-auto d-block mb-2" %>
      <% else %>
        <%= image_tag "house_placeholder.png", width: "80px", class: "rounded-circle mx-auto d-block" %>
      <% end %>

      <ul>
        <li>Name: <%= @house.user.firstName %> <%= @house.user.lastName %></li>
        <li>Rating: TODO add @rating to User</li>
        <li></li>
      </ul>
    </div>
  </div>

    <div class="container d-flex justify-content-center mt-4">
      <% if @house.booked == false && Notification.find_by(house_id: @house.id).nil? %>
       <%= link_to "Request a booking to the Host!", new_house_notification_path(@house), class:"btn-lg btn-primary" %>
      <% else %>
        <%= link_to "A request to book this place is ongoing...", new_house_booking_path(@house), class:"btn btn-primary disabled"  %>
      <% end %>
    </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "DreamPlacesLogo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


      <%= form_with url: houses_path, method: :get, class:"d-flex search-bar" do %>
        <div class="input-group">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a place ex.Lisbon"
          %>
          <span class="input-group-btn">
            <%= submit_tag "Search", class: "btn btn-danger search-button" %>
          </span>
        </div>
      <% end %>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Messages', chatrooms_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <div class="nav-notif">
              <%= link_to "Notifications",  notification_panel_path(NotificationPanel.find_by(user_id: current_user.id).id), class: "nav-link" %>
            </div>
            <% if Notification.where(user_id: current_user.id).count > 0  %>
              <div class="notification-icon rounded-circle d-flex justify-content-center" id="unread_count">
                <p><%= Notification.where(user_id: current_user.id).count %></p>
              </div>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.picture.attached?  %>
              <%= cl_image_tag current_user.picture_small.key, class: "dropdown-toggle rounded-circle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "userPlaceholder.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_pages_profile_path(current_user), class: "dropdown-item" %>
              <%= link_to "Dashboard", pages_dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>