config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  unauthenticated :user do
    root to: "pages#home"
  end
  authenticated do
    root to: "houses#index", as: :authenticated_root
  end
  # get "pages/home", to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:update], as: "update"
  get "pages/dashboard", to: "pages#dashboard"

  resources :users do
    get "pages/profile", to: "pages#profile"
    member do
      put "picture_update"
    end
  end

  resources :houses, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
    resources :notifications, only: [:new, :create]
  end

  delete "notifications/:id", to: "notifications#destroy", as: "delete_notification"

  resources :notifications, only: [:index, :show] do
    collection do
      get :user_personal
    end
  end

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end

  resources :bookings, only: [:index] do
    resources :chatrooms, only: :create
    collection do
      get :my
    end
  end
  resources :notification_panels, only: :show
end

app/views/pages/dashboard.html.erb
<div class="container d-flex justify-content-around mt-5">
  <div class="row">
    <% if current_user.houses.size > 0  %>
      <div class="col-sm-12">
        <div>
          <h3 class="text-center">My Houses for Hosting</h3>
          <div class="row">
            <div class="my-houses borders">
              <% current_user.houses.each do |house|  %>
                <div class="col-sm-12 d-flex">
                  <div class="card my-3" style="width: 18rem;">
                    <% if house.photos.attached? %>
                      <% house.photos.each do |photo|  %>
                        <%= image_tag photo, width: "500px", class: "card-img-top" %>
                      <% end %>
                    <% else %>
                      <%= image_tag "house_placeholder.png", width: "500px", class: "card-img-top" %>
                    <% end %>
                    <div class ="p-1">
                      <div class="card-title">
                        <h5><strong><%= house.name %></strong></h5>
                      </div>
                      <%= link_to "See more", house_path(house), class: "btn btn-sm btn-danger default-button" %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="col-sm-12 d-flex align-items-center">
        <h3>You're not hosting any place</h3>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-sm d-flex align-items-center justify-content-center"></div>
  </div>

  <div class="row">
    <div class="col-sm-12 d-flex flex-column justify-content-center">
      <div class="search btn-lg btn-danger default-button text-center">
        <%= link_to "Host a place", new_house_path %>
      </div>
      <%# <div class="search btn-lg btn-danger default-button"> %>
        <%# <%= link_to "Booked places", my_bookings_path %>
      <%# </div> %>
    </div>
  </div>
</div>
<hr class="m-5">
<div class="container booked-section">
  <h3><strong>Places where have I been...</strong></h3>
  <div class="row">
  <%if @bookings.empty?%>
    <p> You still have not booked one place! <%=link_to "Start now!", houses_path  %></p>
  <% end %>
    <% @bookings.each do |booking| %>
      <div class="col-sm-4 booked-card">
        <div class="card">
          <div class="row g-0">
            <div class="col-sm-3 me-2 mb-4 mt-3">
              <% if booking.house.photos.attached? %>
                <%booking.house.photos.each do |photo|  %>
                  <%= image_tag photo, class: "card-img-top" %>
                <% end %>
              <% else %>
                <%= image_tag "house_placeholder.png", width: "500px", class: "card-img-top booked-image-size" %>
              <% end %>
            </div>
            <div class="col-sm-8 mt-3">
              <div class="card-title">
                <h5> <strong> <%= booking.house.country %> </strong> </h5>
              </div>
              <div class="card-body p-0">
                <p> Hosted by <%= booking.house.user.firstName %> </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
  <%# <div class="container p-5">
    <div class="d-flex justify-content-center">
      <div class="landing-background d-flex flex-column justify-content-center align-items-center">
        <h1 class="ms-5"><strong>Welcome</strong></h1>
        <h1 class="ms-5"><strong>to</strong></h1>
        <h1 class="ms-5"><strong>Dream Places</strong></h1>
      </div>
    </div>
  </div> %>
<div data-controller="landing-title">
  <div class="card-category" data-action="load@window->landing-title#titleShow" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1416331108676-a22ccb276e35?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1734&q=80)">
    <h1 class="hidden-text" data-landing-title-target="title">Welcome to Dream Places</h1>
  </div>
  <div class="container">
    <div class="row mt-3">
      <div class="col-5 hidden-text" style="border:1px solid grey; height: 200px; transition: 1s;" data-landing-title-target="content1"></div>
      <div class="col-2"></div>
      <div class="col-5 hidden-text" style="border:1px solid red; height: 200px; transition: 1s;" data-landing-title-target="content2"></div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container p-5">
  <div class="row profile-row">
    <div class="col-sm-4 borders">
      <div class="picture-section d-flex flex-column align-items-center mt-4">
        <div class="avatar-section">
          <% if @user.picture.attached?  %>
            <%= cl_image_tag @user.picture.key, width: 200, height: 200, crop: :thumb, gravity: :face, class: "rounded-circle mb-2" %>
          <% else %>
            <%= image_tag "userPlaceholder.png", class: "avatar-profile mb-2" %>
          <% end %>
        </div>
        <% if current_user == @user %>
          <%= simple_form_for(@user, as: :user, url: picture_update_user_path(@user), html: {method: :put}) do |f| %>
            <div class="form-inputs">
              <%= f.input :picture, as: :file, label: false %>
            </div>
            <div class="form-actions mt-2 profile-links text-center">
            <%= f.button :submit, "Update image", class: "submit-button" %>
            </div>

          <% end %>
        <% end %>


      </div>
      <hr class="hr-tweak">
      <div class="extra-section ms-3">
        <h3> <strong>User confirmed</strong></h3>
        <ul class="ps-0">
          <li class="mb-2"><i class="fa-solid fa-check me-2"></i>Identity</li>
          <li><i class="fa-solid fa-check me-2"></i>Phone number</li>
        </ul>
        (#TODO)
      </div>
    </div>
    <div class="col-sm"></div>
    <div class="col-sm-6">
      <h2 class="mt-5 ms-3"><strong>Hi, my name is <%= @user.firstName.capitalize %></strong></h2>
      <p class="ms-3">Member since <%= @user.created_at.year %></p>
      <p class="ms-3"><strong><%= link_to "Edit profile", "#", class:"profile-links" if current_user == @user %></strong></p>
    </div>
  </div>
</div>